In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = pd.read_csv(r"C:\Users\KAsab\Downloads\Iris.csv")

In [5]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
X = iris.iloc[:,1:5].values


In [7]:
y = iris.iloc[:,-1].values.ravel()


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 1)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [11]:
scaler = StandardScaler()

In [12]:
lr = LogisticRegression()

In [13]:
model = make_pipeline(scaler,lr)

In [14]:
model.fit(X_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [15]:
lr.fit(X_train,y_train)

LogisticRegression()

In [16]:
lr.score(X_test,y_test)

0.9666666666666667

In [17]:
X2_train,X2_test,y2_train,y2_test = train_test_split(X,y,test_size = 0.2,random_state = 12)

In [18]:
lr.fit(X2_train,y2_train)

LogisticRegression()

In [19]:
lr.score(X2_test,y2_test)

0.9666666666666667

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
cvs = cross_val_score(model,X,y,cv = 10)

In [22]:
cvs

array([1.        , 0.93333333, 1.        , 1.        , 0.93333333,
       0.93333333, 0.8       , 1.        , 1.        , 1.        ])

In [23]:
np.average(cvs)

0.9600000000000002

In [24]:
np.std(cvs)

0.06110100926607785

In [25]:
from sklearn.model_selection import KFold

In [26]:
kf = KFold(n_splits = 15,shuffle = True,random_state = 123)

In [37]:
kf_score = cross_val_score(model, X, y, cv=kf, scoring="accuracy")


In [38]:
kf_score

array([1. , 1. , 0.9, 0.9, 1. , 1. , 1. , 1. , 0.9, 0.9, 0.9, 1. , 1. ,
       1. , 0.8])

In [29]:
np.average(kf_score)

nan

In [30]:
np.std(kf_score)

nan

In [31]:
from sklearn.model_selection import StratifiedKFold

In [32]:
kf2 = StratifiedKFold(n_splits = 10,shuffle = True,random_state = 123)

In [33]:
kfscore2 = cross_val_score(model,X,y,cv = kf2)

In [34]:
kfscore2

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       0.8       , 1.        , 1.        , 0.8       , 0.93333333])

In [35]:
np.average(kfscore2)

0.9533333333333334

In [36]:
np.std(kfscore2)

0.07916228058025276