In [2]:
#tensors are arrays for Pytorch
# basic building block for Pytorch

In [3]:
import torch 
import numpy as np

In [4]:
tensor_1 = torch.tensor([1,2,3])
print("Our first PyTorch Tensor: ",tensor_1)

Our first PyTorch Tensor:  tensor([1, 2, 3])


In [5]:
array_1 = np.array([1,2,3])

In [6]:
tensor_from_numpy = torch.tensor(array_1)
print("PyTorch Tensor from Numpy array: ",tensor_from_numpy)

PyTorch Tensor from Numpy array:  tensor([1, 2, 3], dtype=torch.int32)


In [7]:
empty_tensor = torch.empty(3)
print("Empty Tensor:",empty_tensor)

Empty Tensor: tensor([0., 0., 0.])


In [8]:
zero_tensor = torch.zeros(2,3)
print("Zero Tensor: ",zero_tensor)

Zero Tensor:  tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
one_tensor = torch.ones(2,3)
print("One Tensor: ",one_tensor)

One Tensor:  tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [10]:
random_tensor = torch.rand(3,3)
print("Random Tensor",random_tensor)

Random Tensor tensor([[0.0964, 0.0462, 0.6450],
        [0.1465, 0.8087, 0.5540],
        [0.1597, 0.8963, 0.6324]])


In [11]:
arange_tensor = torch.arange(start = 0,end = 101,step =10)
print("Arange Tensor: ",arange_tensor)

Arange Tensor:  tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])


In [12]:
random_tensor[1,1]

tensor(0.8087)

In [13]:
random_tensor[1,:]

tensor([0.1465, 0.8087, 0.5540])

In [14]:
random_tensor[:,0]

tensor([0.0964, 0.1465, 0.1597])

In [15]:
random_tensor[1,1].item()

0.8086925148963928

In [16]:
reshape_tensor = torch.rand(5,4)
print("Reshape Tensor",reshape_tensor)

Reshape Tensor tensor([[0.5124, 0.7036, 0.5884, 0.0080],
        [0.5973, 0.7456, 0.4199, 0.9667],
        [0.6721, 0.5891, 0.1674, 0.8587],
        [0.3182, 0.4861, 0.8327, 0.1498],
        [0.4722, 0.6041, 0.3753, 0.9172]])


In [17]:
new_reshape_tensor = reshape_tensor.view(-1,2)
print("Reshape Tensor 2: ",new_reshape_tensor)

Reshape Tensor 2:  tensor([[0.5124, 0.7036],
        [0.5884, 0.0080],
        [0.5973, 0.7456],
        [0.4199, 0.9667],
        [0.6721, 0.5891],
        [0.1674, 0.8587],
        [0.3182, 0.4861],
        [0.8327, 0.1498],
        [0.4722, 0.6041],
        [0.3753, 0.9172]])


In [18]:
tensor_a = torch.tensor([1,2,3])
tensor_b = torch.tensor([2,4,6])

In [19]:
results_add_1 = torch.add(tensor_b,tensor_a)
results_add_2= tensor_b + tensor_a
results_sub_1 = tensor_b - tensor_a

print(results_add_1)
print(results_add_2)
print(results_sub_1)

tensor([3, 6, 9])
tensor([3, 6, 9])
tensor([1, 2, 3])


In [20]:
tensor_b.add_(tensor_a)

tensor([3, 6, 9])

In [21]:
print(tensor_b)

tensor([3, 6, 9])


In [22]:
matrix_a = torch.tensor([[1,2],[3,4]])
matrix_b = torch.tensor([[5,6],[7,8]])

In [23]:
results_multiply = torch.mm(matrix_a,matrix_b)
print(results_multiply)

tensor([[19, 22],
        [43, 50]])


In [24]:
print(matrix_a)
print(matrix_b)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])


In [25]:
results_multiply2 = torch.mul(matrix_a,matrix_b)
print(results_multiply2)

tensor([[ 5, 12],
        [21, 32]])


In [26]:
results_multiply.dtype

torch.int64

In [27]:
random_tensor.dtype

torch.float32

In [28]:
tensor_int = torch.tensor([4,5,6],dtype = torch.int64)
print(tensor_int)
print(tensor_int.dtype)

tensor([4, 5, 6])
torch.int64


In [29]:
tensor_float = tensor_int.to(torch.float32)

In [30]:
tensor_float.dtype

torch.float32

In [42]:
tensor_float.device

device(type='cpu')

In [43]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [47]:
tensor_float.to(device)

tensor([4., 5., 6.])

In [34]:
tensor_float.device

device(type='cpu')

In [56]:
torch.cuda.is_available()

False

In [59]:
torch.cpu.device_count()

1

In [60]:
import torch
import torchvision
import torchvision.transforms as transforms

In [61]:
transform = transforms.Compose(
    [transforms.ToTensor(),
    transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))]
)

In [63]:
trainset = torchvision.datasets.CIFAR10(root = "./downloads",train = True,
                                       download = True,transform = transform)

Files already downloaded and verified


In [79]:
x = torch.tensor([3.0],dtype = torch.float32,requires_grad = True)

In [81]:
y = x**2 + 4

In [82]:
y.backward()

In [83]:
print("Gradient: x",x.grad)

Gradient: x tensor([6.])


In [85]:
x = torch.tensor([3.0])
y = torch.tensor(7.0)

In [ ]:
x.requires_grad_(True)