In [105]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [106]:
diabetes = pd.read_csv(r"C:\Users\KAsab\Downloads\diabetes.csv")

In [107]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [108]:
cal_housing = pd.read_csv(r"C:\Users\KAsab\Desktop\YOUTUBE R VIDEOS DATASETS\cal_housing_clean.csv")

In [109]:
cal_housing.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
0                41         880            129         322         126   
1                21        7099           1106        2401        1138   
2                52        1467            190         496         177   
3                52        1274            235         558         219   
4                52        1627            280         565         259   

   medianIncome  medianHouseValue  
0        8.3252            452600  
1        8.3014            358500  
2        7.2574            352100  
3        5.6431            341300  
4        3.8462            342200

In [110]:
import torch

In [111]:
x = torch.empty(2,3)
print(x)

tensor([[ 1.0842e-19,  1.9778e+00, -1.0842e-19],
        [ 1.9206e+00,  3.6893e+19,  1.6471e+00]])


In [112]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [113]:
print(x.dtype)

torch.float32


In [114]:
torch.ones(2,3,dtype = torch.int)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [115]:
print(x.size())

torch.Size([2, 3])


In [116]:
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [117]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.5396, 0.8503],
        [0.4394, 0.6779]])
tensor([[0.7372, 0.2136],
        [0.3871, 0.0952]])


In [118]:
z = x + y
print(z)

tensor([[1.2767, 1.0639],
        [0.8265, 0.7731]])


In [119]:
z = torch.add(x,y)

In [120]:
y.add_(x)

tensor([[1.2767, 1.0639],
        [0.8265, 0.7731]])

In [121]:
## any function in pytorch with underscore will do in-place operation

In [122]:
c = y.sub_(x)
print(c)

tensor([[0.7372, 0.2136],
        [0.3871, 0.0952]])


In [123]:
m = y.mul_(x)
print(m)

tensor([[0.3977, 0.1816],
        [0.1701, 0.0645]])


In [124]:
y.div(x)

tensor([[0.7372, 0.2136],
        [0.3871, 0.0952]])

In [125]:
y

tensor([[0.3977, 0.1816],
        [0.1701, 0.0645]])

In [126]:
x = torch.rand(5,3)

In [127]:
print(x)

tensor([[0.4436, 0.5003, 0.1042],
        [0.9917, 0.7032, 0.5815],
        [0.4945, 0.1338, 0.8473],
        [0.0625, 0.9152, 0.2969],
        [0.1119, 0.3503, 0.3357]])


In [128]:
print(x[1,1].item()) # will get actual value 

0.7031782269477844


In [129]:
x = torch.rand(4,4)
print(x)

tensor([[0.6221, 0.6069, 0.1610, 0.2062],
        [0.4016, 0.9102, 0.0848, 0.6305],
        [0.4842, 0.8339, 0.0452, 0.2510],
        [0.4625, 0.2745, 0.4846, 0.0062]])


In [130]:
## reshape tensor
y = x.view(2,8)
print(y)

tensor([[0.6221, 0.6069, 0.1610, 0.2062, 0.4016, 0.9102, 0.0848, 0.6305],
        [0.4842, 0.8339, 0.0452, 0.2510, 0.4625, 0.2745, 0.4846, 0.0062]])


In [131]:
y = x.view(-1,8)
print(y.size())

torch.Size([2, 8])


In [132]:
## converting numpy to torch tensor

In [133]:
a  = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [134]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [135]:
##when in cpu  a and b are in the same memory space so modifying one will affect the other 
a.add_(1)
print(a)
print(a)

tensor([2., 2., 2., 2., 2.])
tensor([2., 2., 2., 2., 2.])


In [136]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [137]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [138]:
a+=1

In [139]:
torch.cuda.is_available()

False

In [140]:
# specify requires_grad = True for any tensor u would like to optimize in the future

x = torch.ones(5,requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In PyTorch, `torch.randn()` is a function used to generate a tensor filled with random numbers from a normal distribution (also known as a Gaussian distribution) with a mean of 0 and a standard deviation of 1.

In [141]:
x = torch.randn(3,requires_grad = True)
print(x)

tensor([0.9631, 0.7437, 1.0612], requires_grad=True)


In [142]:
y = x + 2
print(y)

tensor([2.9631, 2.7437, 3.0612], grad_fn=<AddBackward0>)


In [146]:
z = y*y*2
print(z)

tensor([17.5604, 15.0554, 18.7425], grad_fn=<MulBackward0>)


In [151]:
z = z.mean()
print(z)

tensor(17.1194, grad_fn=<MeanBackward0>)


In [149]:
v = torch.tensor([0.1,1.0,0.001],dtype = torch.float32)

In [152]:
z.backward()
print(x.grad)

tensor([7.9017, 7.3164, 8.1633])
