In [1]:
import numpy as np

In [3]:
my_list = [1,2,3,4]
my_array=np.array(my_list)
type(my_array)

numpy.ndarray

In [4]:
second_list= [5,6,7,8]
two_d_array=np.array([my_list,second_list])
print(two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
two_d_array.shape

(2, 4)

In [6]:
two_d_array.size

8

In [7]:
two_d_array.dtype

dtype('int32')

In [8]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.ones(shape=[2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros(shape=[4,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
one_d_array = np.array([1,2,3,4,5,6])
one_d_array[3]


4

In [12]:
one_d_array[3:]

array([4, 5, 6])

In [13]:
one_d_array[::-1]  ## slice whole array but in reverse order

array([6, 5, 4, 3, 2, 1])

In [14]:
two_d_array = np.array([one_d_array,one_d_array +6,one_d_array + 12])
print(two_d_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [17]:
two_d_array[1,4]

11

In [18]:
np.reshape(a=two_d_array,
          newshape=(6,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [19]:
np.ravel(a=two_d_array,
        order="C")

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [20]:
two_d_array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [21]:
two_d_array.T

array([[ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17],
       [ 6, 12, 18]])

In [22]:
np.rot90(two_d_array,
        k=1)

array([[ 6, 12, 18],
       [ 5, 11, 17],
       [ 4, 10, 16],
       [ 3,  9, 15],
       [ 2,  8, 14],
       [ 1,  7, 13]])

In [23]:
two_d_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [24]:
array_to_join = np.array([[10,20,30],[40,50,60],[70,80,90]])
np.concatenate((two_d_array,array_to_join),
              axis=1)

array([[ 1,  2,  3,  4,  5,  6, 10, 20, 30],
       [ 7,  8,  9, 10, 11, 12, 40, 50, 60],
       [13, 14, 15, 16, 17, 18, 70, 80, 90]])

In [25]:
two_d_array+ 100

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118]])

In [26]:
two_d_array -100

array([[-99, -98, -97, -96, -95, -94],
       [-93, -92, -91, -90, -89, -88],
       [-87, -86, -85, -84, -83, -82]])

In [27]:
two_d_array%2

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]], dtype=int32)

In [28]:
np.mean(two_d_array)

9.5

In [29]:
np.mean(two_d_array,
       axis = 1)

array([ 3.5,  9.5, 15.5])

In [30]:
np.std(two_d_array)

5.188127472091127

In [32]:
np.mean(two_d_array,
       axis=1
       )

array([ 3.5,  9.5, 15.5])