In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
iris = pd.read_csv(r"C:\Users\KAsab\Downloads\Iris.csv")

In [4]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
iris.columns = [name.lower() for name in iris.columns]

In [6]:
iris.head()

id  sepallengthcm  sepalwidthcm  petallengthcm  petalwidthcm      species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
iris["species"] = iris["species"].str.split("-").str[1]

In [8]:
iris.head(10)

id  sepallengthcm  sepalwidthcm  petallengthcm  petalwidthcm species
0   1            5.1           3.5            1.4           0.2  setosa
1   2            4.9           3.0            1.4           0.2  setosa
2   3            4.7           3.2            1.3           0.2  setosa
3   4            4.6           3.1            1.5           0.2  setosa
4   5            5.0           3.6            1.4           0.2  setosa
5   6            5.4           3.9            1.7           0.4  setosa
6   7            4.6           3.4            1.4           0.3  setosa
7   8            5.0           3.4            1.5           0.2  setosa
8   9            4.4           2.9            1.4           0.2  setosa
9  10            4.9           3.1            1.5           0.1  setosa

In [9]:
X = iris.iloc[:,1:5]
y = iris["species"]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 123)

In [12]:
X_train.shape

(120, 4)

In [13]:
y_train.shape

(120,)

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
penguins = pd.read_csv(r"C:\Users\KAsab\Downloads\palmerpenguins.csv")

In [18]:
penguins.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  year  
0       3750.0    male  2007  
1       3800.0  female  2007  
2       3250.0  female  2007  
3          NaN     NaN  2007  
4       3450.0  female  2007

In [19]:
penguins.dropna(how = "any",inplace = True)

In [20]:
X1 = penguins.iloc[:,2:6]
X2 = penguins.iloc[:,2:6]


In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scalestandard = StandardScaler()

In [23]:
X1 = scalestandard.fit_transform(X1)

In [24]:
X1

array([[-0.89604189,  0.7807321 , -1.42675157, -0.56847478],
       [-0.82278787,  0.11958397, -1.06947358, -0.50628618],
       [-0.67627982,  0.42472926, -0.42637319, -1.1903608 ],
       ...,
       [ 1.02687621,  0.52644436, -0.56928439, -0.53738048],
       [ 1.24663828,  0.93330475,  0.64546078, -0.13315457],
       [ 1.13675725,  0.7807321 , -0.2120064 , -0.53738048]])

In [25]:
X1

array([[-0.89604189,  0.7807321 , -1.42675157, -0.56847478],
       [-0.82278787,  0.11958397, -1.06947358, -0.50628618],
       [-0.67627982,  0.42472926, -0.42637319, -1.1903608 ],
       ...,
       [ 1.02687621,  0.52644436, -0.56928439, -0.53738048],
       [ 1.24663828,  0.93330475,  0.64546078, -0.13315457],
       [ 1.13675725,  0.7807321 , -0.2120064 , -0.53738048]])

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
scaleminmax = MinMaxScaler()

In [28]:
X2 =scaleminmax.fit_transform(X2)

In [29]:
X2

array([[0.25454545, 0.66666667, 0.15254237, 0.29166667],
       [0.26909091, 0.51190476, 0.23728814, 0.30555556],
       [0.29818182, 0.58333333, 0.38983051, 0.15277778],
       ...,
       [0.63636364, 0.60714286, 0.3559322 , 0.29861111],
       [0.68      , 0.70238095, 0.6440678 , 0.38888889],
       [0.65818182, 0.66666667, 0.44067797, 0.29861111]])

In [30]:
dfx2 = pd.DataFrame(X2,columns = ["bill_length_mm","bill_depth_mm","flipper_length_mm","body_mass_g"])

In [31]:
dfx2.describe()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      333.000000     333.000000         333.000000   333.000000
mean         0.432465       0.483912           0.490966     0.418627
std          0.198861       0.234433           0.237555     0.223671
min          0.000000       0.000000           0.000000     0.000000
25%          0.269091       0.297619           0.305085     0.236111
50%          0.450909       0.500000           0.423729     0.375000
75%          0.600000       0.666667           0.694915     0.576389
max          1.000000       1.000000           1.000000     1.000000

In [32]:
X = penguins[["island","sex"]]
y = penguins["species"]

In [33]:
X.head()

island     sex
0  Torgersen    male
1  Torgersen  female
2  Torgersen  female
4  Torgersen  female
5  Torgersen    male

In [34]:
y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [35]:
X["sex"].unique()

array(['male', 'female'], dtype=object)

In [36]:
X["island"].unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [37]:
from sklearn.preprocessing import OneHotEncoder

In [38]:
ohe = OneHotEncoder(sparse_output = False,handle_unknown = 'ignore').set_output (transform = "pandas")

In [39]:
ohetransform= ohe.fit_transform(penguins[["species","island","sex"]])

In [40]:
ohetransform.head()

species_Adelie  species_Chinstrap  species_Gentoo  island_Biscoe  \
0             1.0                0.0             0.0            0.0   
1             1.0                0.0             0.0            0.0   
2             1.0                0.0             0.0            0.0   
4             1.0                0.0             0.0            0.0   
5             1.0                0.0             0.0            0.0   

   island_Dream  island_Torgersen  sex_female  sex_male  
0           0.0               1.0         0.0       1.0  
1           0.0               1.0         1.0       0.0  
2           0.0               1.0         1.0       0.0  
4           0.0               1.0         1.0       0.0  
5           0.0               1.0         0.0       1.0

In [41]:
df = pd.concat([penguins,ohetransform],axis = 1).drop(columns = ["species","island","sex"])

In [42]:
df.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  year  \
0            39.1           18.7              181.0       3750.0  2007   
1            39.5           17.4              186.0       3800.0  2007   
2            40.3           18.0              195.0       3250.0  2007   
4            36.7           19.3              193.0       3450.0  2007   
5            39.3           20.6              190.0       3650.0  2007   

   species_Adelie  species_Chinstrap  species_Gentoo  island_Biscoe  \
0             1.0                0.0             0.0            0.0   
1             1.0                0.0             0.0            0.0   
2             1.0                0.0             0.0            0.0   
4             1.0                0.0             0.0            0.0   
5             1.0                0.0             0.0            0.0   

   island_Dream  island_Torgersen  sex_female  sex_male  
0           0.0               1.0         0.0       1.0  
1           0.0               1.0         1.0       0.0  
2           0.0               1.0         1.0       0.0  
4           0.0               1.0         1.0       0.0  
5           0.0               1.0         0.0       1.0

In [43]:
from sklearn.preprocessing import MinMaxScaler

In [44]:
mms = MinMaxScaler().set_output(transform = "pandas")

In [45]:
minmax = mms.fit_transform(penguins.iloc[:,2:6])

In [46]:
minmax.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0        0.254545       0.666667           0.152542     0.291667
1        0.269091       0.511905           0.237288     0.305556
2        0.298182       0.583333           0.389831     0.152778
4        0.167273       0.738095           0.355932     0.208333
5        0.261818       0.892857           0.305085     0.263889

In [47]:
df = pd.concat([minmax,ohetransform],axis = 1)

In [48]:
df.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0.254545       0.666667           0.152542     0.291667   
1        0.269091       0.511905           0.237288     0.305556   
2        0.298182       0.583333           0.389831     0.152778   
4        0.167273       0.738095           0.355932     0.208333   
5        0.261818       0.892857           0.305085     0.263889   

   species_Adelie  species_Chinstrap  species_Gentoo  island_Biscoe  \
0             1.0                0.0             0.0            0.0   
1             1.0                0.0             0.0            0.0   
2             1.0                0.0             0.0            0.0   
4             1.0                0.0             0.0            0.0   
5             1.0                0.0             0.0            0.0   

   island_Dream  island_Torgersen  sex_female  sex_male  
0           0.0               1.0         0.0       1.0  
1           0.0               1.0         1.0       0.0  
2           0.0               1.0         1.0       0.0  
4           0.0               1.0         1.0       0.0  
5           0.0               1.0         0.0       1.0

In [49]:
penguins.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  year  
0       3750.0    male  2007  
1       3800.0  female  2007  
2       3250.0  female  2007  
4       3450.0  female  2007  
5       3650.0    male  2007

In [50]:
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler,StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer

In [51]:
ohe = OneHotEncoder(sparse_output = False,handle_unknown = "ignore").set_output(transform = "pandas")
ss = StandardScaler().set_output(transform = "pandas")
imp = SimpleImputer()


In [52]:
ct = make_column_transformer(
    (ohe,["sex","island"]),
    (ss,[2,3,4,5]),
    ("drop",["year"]),
    remainder = "passthrough"
)

In [53]:
ct.set_output(transform = "pandas")

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['sex', 'island']),
                                ('standardscaler', StandardScaler(),
                                 [2, 3, 4, 5]),
                                ('drop', 'drop', ['year'])])

In [54]:
df2 = ct.fit_transform(penguins)

In [55]:
df2

onehotencoder__sex_female  onehotencoder__sex_male  \
0                          0.0                      1.0   
1                          1.0                      0.0   
2                          1.0                      0.0   
4                          1.0                      0.0   
5                          0.0                      1.0   
..                         ...                      ...   
339                        0.0                      1.0   
340                        1.0                      0.0   
341                        0.0                      1.0   
342                        0.0                      1.0   
343                        1.0                      0.0   

     onehotencoder__island_Biscoe  onehotencoder__island_Dream  \
0                             0.0                          0.0   
1                             0.0                          0.0   
2                             0.0                          0.0   
4                             0.0                          0.0   
5                             0.0                          0.0   
..                            ...                          ...   
339                           0.0                          1.0   
340                           0.0                          1.0   
341                           0.0                          1.0   
342                           0.0                          1.0   
343                           0.0                          1.0   

     onehotencoder__island_Torgersen  standardscaler__bill_length_mm  \
0                                1.0                       -0.896042   
1                                1.0                       -0.822788   
2                                1.0                       -0.676280   
4                                1.0                       -1.335566   
5                                1.0                       -0.859415   
..                               ...                             ...   
339                              0.0                        2.162314   
340                              0.0                       -0.090248   
341                              0.0                        1.026876   
342                              0.0                        1.246638   
343                              0.0                        1.136757   

     standardscaler__bill_depth_mm  standardscaler__flipper_length_mm  \
0                         0.780732                          -1.426752   
1                         0.119584                          -1.069474   
2                         0.424729                          -0.426373   
4                         1.085877                          -0.569284   
5                         1.747026                          -0.783651   
..                             ...                                ...   
339                       1.340165                           0.431094   
340                       0.475587                           0.073816   
341                       0.526444                          -0.569284   
342                       0.933305                           0.645461   
343                       0.780732                          -0.212006   

     standardscaler__body_mass_g remainder__species  
0                      -0.568475             Adelie  
1                      -0.506286             Adelie  
2                      -1.190361             Adelie  
4                      -0.941606             Adelie  
5                      -0.692852             Adelie  
..                           ...                ...  
339                    -0.257532          Chinstrap  
340                    -1.003795          Chinstrap  
341                    -0.537380          Chinstrap  
342                    -0.133155          Chinstrap  
343                    -0.537380          Chinstrap  

[333 rows x 10 columns]

In [56]:
df2.isna().sum()

onehotencoder__sex_female            0
onehotencoder__sex_male              0
onehotencoder__island_Biscoe         0
onehotencoder__island_Dream          0
onehotencoder__island_Torgersen      0
standardscaler__bill_length_mm       0
standardscaler__bill_depth_mm        0
standardscaler__flipper_length_mm    0
standardscaler__body_mass_g          0
remainder__species                   0
dtype: int64

### Pipelines

In [57]:
iris.head()

id  sepallengthcm  sepalwidthcm  petallengthcm  petalwidthcm species
0   1            5.1           3.5            1.4           0.2  setosa
1   2            4.9           3.0            1.4           0.2  setosa
2   3            4.7           3.2            1.3           0.2  setosa
3   4            4.6           3.1            1.5           0.2  setosa
4   5            5.0           3.6            1.4           0.2  setosa

In [58]:
X = iris.iloc[:,1:5]
y = iris.iloc[:,5]

In [59]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 123)

In [60]:
X_train.shape

(120, 4)

In [61]:
y_train.shape

(120,)

In [62]:
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

In [63]:
imputer = SimpleImputer(strategy = "mean")

In [64]:
lr = LogisticRegression()

In [65]:
from sklearn.pipeline import make_pipeline

In [66]:
pipe1 = make_pipeline(imputer,lr)

In [67]:
pipe1.fit(X_train,y_train)

Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('logisticregression', LogisticRegression())])

In [68]:
pipe1.score(X_train,y_train)

0.9833333333333333

In [69]:
pipe1.score(X_test,y_test)

1.0

In [70]:
pipe1.named_steps.simpleimputer.statistics_

array([5.86916667, 3.04083333, 3.82083333, 1.22333333])

In [71]:
pipe1.named_steps.logisticregression.coef_

array([[-0.41606294,  0.96326999, -2.40705664, -1.0111681 ],
       [ 0.48691587, -0.18165205, -0.20067611, -0.81786118],
       [-0.07085293, -0.78161794,  2.60773274,  1.82902928]])

### Advanced Pipeline

In [72]:
penguins.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  year  
0       3750.0    male  2007  
1       3800.0  female  2007  
2       3250.0  female  2007  
4       3450.0  female  2007  
5       3650.0    male  2007

In [73]:
X = penguins.iloc[:,0:6]
y = penguins.iloc[:,6]

In [74]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 123)

In [75]:
num_cols = ["bill_length_mm","bill_depth_mm","flipper_length_mm","body_mass_g"]
cat_cols = ["island","species"]

In [76]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [77]:
num_pipeline = Pipeline(
   steps= [
    ("impute",SimpleImputer(strategy = "mean")),
    ("scale",StandardScaler())
   ] )

In [78]:
cat_pipeline = Pipeline(steps = [
    ("impute",SimpleImputer(strategy = "most_frequent")),
    ("one_hot_encoder",OneHotEncoder(handle_unknown = "ignore",sparse_output = False))
])

In [79]:
col_transformer = ColumnTransformer(transformers = [
    ("num_pipeline",num_pipeline,num_cols),
    ("cat_pipeline",cat_pipeline,cat_cols)
],
  remainder = "drop",
   n_jobs =-1                                )

In [80]:
from sklearn.tree import DecisionTreeClassifier

In [81]:
dtc = DecisionTreeClassifier()

In [82]:
pipefinal = make_pipeline(col_transformer,dtc)

In [83]:
pipefinal.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(n_jobs=-1,
                                   transformers=[('num_pipeline',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer()),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['bill_length_mm',
                                                   'bill_depth_mm',
                                                   'flipper_length_mm',
                                                   'body_mass_g']),
                                                 ('cat_pipeline',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('one_hot_encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['island', 'species'])])),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [84]:
pipefinal.score(X_test,y_test)

0.76

In [85]:
# how to save your pipeline

In [86]:
import joblib

In [87]:
joblib.dump(pipefinal,"pipe_joblib")

['pipe_joblib']

In [88]:
pipefinal2 = joblib.load("pipe_joblib")

### **CALIFORNIA HOUSING**

In [89]:
housing = pd.read_csv(r"C:\Users\KAsab\Downloads\Compressed\archive_37\california_housing.csv")

In [90]:
housing.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [ ]:
housing.

In [124]:
X = housing.iloc[:,:-2].to_numpy()
X


array([[-1.2223e+02,  3.7880e+01,  4.1000e+01, ...,  3.2200e+02,
         1.2600e+02,  8.3252e+00],
       [-1.2222e+02,  3.7860e+01,  2.1000e+01, ...,  2.4010e+03,
         1.1380e+03,  8.3014e+00],
       [-1.2224e+02,  3.7850e+01,  5.2000e+01, ...,  4.9600e+02,
         1.7700e+02,  7.2574e+00],
       ...,
       [-1.2122e+02,  3.9430e+01,  1.7000e+01, ...,  1.0070e+03,
         4.3300e+02,  1.7000e+00],
       [-1.2132e+02,  3.9430e+01,  1.8000e+01, ...,  7.4100e+02,
         3.4900e+02,  1.8672e+00],
       [-1.2124e+02,  3.9370e+01,  1.6000e+01, ...,  1.3870e+03,
         5.3000e+02,  2.3886e+00]])

In [132]:
y= housing.iloc[:,-2].to_numpy()

In [133]:
y

array([452600., 358500., 352100., ...,  92300.,  84700.,  89400.])

In [134]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 123)

In [135]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((14448, 8), (6192, 8), (14448,), (6192,))

In [109]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler,FunctionTransformer
from copy import deepcopy

housing_median_age  total_rooms  total_bedrooms  population  \
12364                 6.0       4863.0           920.0      3010.0   
12271                21.0       4624.0           852.0      2174.0   
19605                32.0        946.0           198.0       624.0   
10600                 8.0       2032.0           349.0       862.0   
45                   52.0       1656.0           420.0       718.0   
...                   ...          ...             ...         ...   
7763                 36.0        726.0             NaN       490.0   
15377                14.0       4687.0           793.0      2436.0   
17730                 5.0       4153.0           719.0      2435.0   
15725                44.0       1545.0           334.0       561.0   
19966                20.0       1911.0           389.0      1241.0   

       households  median_income  
12364       828.0         3.9508  
12271       812.0         3.5255  
19605       173.0         1.9728  
10600       340.0         6.9133  
45          382.0         2.6768  
...           ...            ...  
7763        130.0         3.6389  
15377       779.0         4.5391  
17730       697.0         5.6306  
15725       326.0         3.8750  
19966       348.0         2.5156  

[14448 rows x 6 columns]

In [136]:
std_scaler = StandardScaler().fit(X_train[:,:2])
mms = MinMaxScaler().fit(X_train[:,2:])

In [137]:
def preprocessor(X):
    A = np.copy(X)
    A[:,:2]= std_scaler.transform(X[:,:2])
    A[:,2:]= mms.transform(X[:,2:])
    return A

In [138]:
preprocessor(X_test)

array([[-1.52801164,  1.22038832,  0.76470588, ...,  0.06355048,
         0.07410864,  0.22701756],
       [ 0.26231782,  0.21408367,  0.15686275, ...,  0.10710342,
         0.10584282,  0.24287941],
       [ 1.29462478, -1.30239402,  0.21568627, ...,  0.20353331,
         0.12413664,  0.24746555],
       ...,
       [ 0.84579567, -0.90455265,  0.31372549, ...,  0.18175684,
         0.24976666,  0.20576268],
       [ 0.60143315, -0.73137464,  1.        , ...,  0.05496258,
         0.07149524,  0.25862402],
       [ 0.54158927, -0.63776491,  0.62745098, ...,  0.09661391,
         0.09445585,  0.28138233]])

In [141]:
preprocess_transformer = FunctionTransformer(preprocessor)

In [143]:
from sklearn.linear_model import LinearRegression

In [144]:
lr = LinearRegression()

In [160]:
p1 = Pipeline(steps = [
    ("Impute",SimpleImputer(strategy = "mean")),
    ("Scaler",preprocess_transformer),
("Linear Regression",lr),
])

In [161]:
p1

Pipeline(steps=[('Impute', SimpleImputer()),
                ('Scaler',
                 FunctionTransformer(func=<function preprocessor at 0x0000019048BF4540>)),
                ('Linear Regression', LinearRegression())])

In [150]:
from sklearn.metrics import mean_absolute_error

In [155]:
def fit_and_print(p,X_train = X_train,y_train = y_train,X_test= X_test,y_test= y_test):
    p.fit(X_train,y_train)
    train_preds = p.predict(X_train)
    test_preds = p.predict(X_test)
    print("Training error: " + str(mean_absolute_error(train_preds,y_train)))
    print("Test error: " + str(mean_absolute_error(test_preds,y_test)))

In [162]:
fit_and_print(p1)

Training error: 51219.96686531341
Test error: 50348.08626259619


In [170]:
from sklearn.neighbors import KNeighborsRegressor  as KNR

In [173]:
p2 = Pipeline(steps=[
    ("Imputer",SimpleImputer(strategy = "mean")),
    ("Scaler",preprocess_transformer),
    ("KNN Regression",KNR(n_neighbors = 7))
])
fit_and_print(p2)

Training error: 30666.48820400253
Test error: 35016.51435031377


In [174]:
p2

Pipeline(steps=[('Imputer', SimpleImputer()),
                ('Scaler',
                 FunctionTransformer(func=<function preprocessor at 0x0000019048BF4540>)),
                ('KNN Regression', KNeighborsRegressor(n_neighbors=7))])